[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/projector"
  to = "/projector.html"
  status = 301
  force = true

[[redirects]]
  from = "/tree-topper"
  to = "/tree-topper.html"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301
  force = true

[[redirects]]
  from = "/snow-globe"
  to = "/snow-globe.html"
  status = 301
  force = true

[[redirects]]
  from = "/halloween"
  to = "/halloween.html"
  status = 301
  force = true

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 301
  force = true

[[redirects]]
  from = "/es/halloween"
  to = "/es/halloween.html"
  status = 301
  force = true

[[redirects]]
  from = "/es/faq"
  to = "/es/faq.html"
  status = 301
  force = true

[[redirects]]
  from = "/es/projector"
  to = "/es/projector.html"
  status = 301
  force = true
